import { createStore } from "redux";
const functions=require('./actions.js');
export const initialstate=[0];
const app=initialstate;

// const arr=[[
//     {  src:"",
//     rate:0,
//     productName:"",
//     Quantity:0,
//     cost:0,},
//     {  src:"",
//     rate:0,
//     productName:"",
//     Quantity:0,
//     cost:0,},
//     {  src:"",
//     rate:0,
//     productName:"",
//     Quantity:0,
//     cost:0,},
//     {  src:"",
//     rate:0,
//     productName:"",
//     Quantity:0,
//     cost:0,},
//     {  src:"",
//     rate:0,
//     productName:"",
//     Quantity:0,
//     cost:0,}
// ],

// [{  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,}],

// [{  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,}],

// [{  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,}],

// [{  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,}],

// [{  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,}],

// [{  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,}],

// [{  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,}],

// [{  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},

// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,}],

// [{  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,}],
// [{  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,}],

// [{  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},

// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,}],

// [{  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,}],

// [{  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,}],

// [{  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,}],

// [{  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,}],

// [{  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,},
// {  src:"",
// rate:0,
// productName:"",
// Quantity:0,
// cost:0,}]
// ];

// const initialObj={
//     src:"",
//     rate:0,
//     productName:"",
//     Quantity:0,
//     cost:0,
    
// }

// 'Women clothing',
//            'Men clothing',
//            'Kids SchoolDress',
//            'Jwellery',
//            'Stationary',
//            'Electronics',
//             'Books',
//             'gadgets',
//             'Women Western-Wear',
//             'Women Indian-Wear',
//             'Cosmetics',
//             'Footwear',
//             'Men Traditional Attire',
//             'Perfumes',
//             'Wristwatch',
//             'Groceries',
//             'Daily-wears',


const reducer=(state=initialstate,action)=>{
switch(action.type){
    case "ADD_TO_CART":
        console.log(action);
            console.log(state);
               console.log(state===app);
               state[0]=state[0]+action.payload.rate;
                return [...state,action.payload];
            
        
        //  case "INCREAMENT_QUANTITY":
        //     const index=state.indexOf(ob);
        //     state[0]={
        //         totalPrice: state[0].totalPrice+ob.rate,
        //         count:state[0].count
        //     }
        //     return{
        //     state:[
        //         ...state.slice(0,index),{
        //             ...ob,Quantity:ob.Quantity+1,cost:ob.cost+ob.rate
        //         },...state.slice(index)
        //     ]
               
        //     }
        
        // case "DECREAMENT_QUANTITY":
        //     const ind=state.indexOf(ob);
        //     state[0]={
        //         totalPrice:ob.totalPrice>=ob.rate&& state[0].totalPrice-ob.rate,
        //         count:state[0].count
        //     }
        //     return{
        //     state:[
        //         ...state.slice(0,ind),{
        //             ...ob,Quantity:ob.Quantity>=1&&ob.Quantity-1,cost:ob.cost>=ob.rate&&ob.cost-ob.rate
        //         },...state.slice(ind)
        //     ]
               
        //     }
            default :return state;
}
}
const store=createStore(reducer,initialstate,window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__());


export default store;